version: 0.2

phases:
  pre_build:
    commands:
      - echo "Authenticating with CodeArtifact..."
      - export CODEARTIFACT_TOKEN=$(aws codeartifact get-authorization-token --domain $CODEARTIFACT_DOMAIN --domain-owner $CODEARTIFACT_DOMAIN_OWNER --query authorizationToken --output text)
      - export CODEARTIFACT_URL=$(aws codeartifact get-repository-endpoint --domain $CODEARTIFACT_DOMAIN --domain-owner $CODEARTIFACT_DOMAIN_OWNER --repository pip-repo --format pypi --query repositoryEndpoint --output text)
      - export CODEARTIFACT_CARGO_URL=$(aws codeartifact get-repository-endpoint --domain $CODEARTIFACT_DOMAIN --domain-owner $CODEARTIFACT_DOMAIN_OWNER --repository cargo-repo --format cargo --query repositoryEndpoint --output text)
      - echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - docker buildx create --use --driver docker-container
  build:
    commands:
      - echo "Building Docker image..."
      - docker buildx build
          --cache-from type=s3,region=${AWS_REGION},bucket=${CACHE_BUCKET},prefix=${CACHE_PREFIX}/
          --cache-to type=s3,region=${AWS_REGION},bucket=${CACHE_BUCKET},prefix=${CACHE_PREFIX}/,mode=max
          --build-arg CODEARTIFACT_URL="${CODEARTIFACT_URL}"
          --build-arg CODEARTIFACT_CARGO_URL="${CODEARTIFACT_CARGO_URL}"
          --build-arg CODEARTIFACT_TOKEN="${CODEARTIFACT_TOKEN}"
          --secret id=token,env=CODEARTIFACT_TOKEN
          -t py-duckling-native
          --load
          .
  post_build:
    commands:
      - echo "Package published to CodeArtifact pip-repo"

cache:
  paths:
    - "/tmp/docker-cache/**/*"
